using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HC.Patient.Entity
{
    public class Chat : BaseEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("Id")]

        public int Id { get; set; }
        public string Message { get; set; }
        public bool IsSeen { get; set; }
        public int? PatientCareGapID { get; set; }
        public bool? IsConfirmType { get; set; }
        public string ResponseCode { get; set; }
        public DateTime? ResponseTime { get; set; }
        public bool? AutoGeneratedFlag { get; set; }
        public DateTime? AutoGeneratedMessageTime { get; set; }

        [ForeignKey("FromUser")]
        public int FromUserId { get; set; }

        [ForeignKey("ToUser")]
        public int ToUserId { get; set; }

        [ForeignKey("CareGapMessageTemplate")]
        public int? CareGapMessageTemplateId { get; set; }

        public DateTime ChatDate { get; set; }
        public int OrganizationID { get; set; }
        public bool? IsAcknowledged { get; set; }
        public DateTime? Acknowledged { get; set; }
        public bool? IsPOC { get; set; }
        
        [ForeignKey("GlobalCode")]
        public int? POCHugsTypeId { get; set; }

        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual CareGapMessageTemplate CareGapMessageTemplate { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }

    }
}
